config/routes.rb
Rails.application.routes.draw do

  resources :students, only: [:index, :create] do
    collection do
      put :call_on
    end
  end

end

app/models/student.rb
class Student < ActiveRecord::Base
  before_create :populate_default_values

  validates_presence_of :name

  default_scope -> { order("called_on ASC NULLS first") }
  scope :not_called_on_today, -> { where("called_on <= ?", DateTime.now.prev_day) }

  def self.pick_random
    students = Student.not_called_on_today
    student = students.sample
  end

  protected

  def populate_default_values
    self.called_on ||= DateTime.new(1, 1, 1)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path, notice: "#{@student.name} has been added to the list."
    else
      flash.now[:alert] = "Student could not be added."
      @students = Student.all
      render :index
    end
  end

  def call_on
    student = Student.pick_random
    student.update(called_on: DateTime.now)
    redirect_to students_path, notice: "#{student.name} has been chosen."
  end

  protected

  def student_params
    params.require(:student).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? yield(:title) : "Call On"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
    <script type="text/javascript" src="//use.typekit.net/ayn0ftv.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  %body
    %main
      - if notice.present?
        .alert-box.success{ "data-alert" => "" }
          = notice
          %a.close{ href: "#" } &times;
      - if alert.present?
        .alert-box.alert{ "data-alert" => "" }
          = alert
          %a.close{ href: "#" } &times;
      = yield

    = javascript_include_tag "application"
    = javascript_tag '$.fx.off = true;' if Rails.env.test?

app/views/students/_student.html.haml
%li= student.name
- if student.called_on == DateTime.new(1, 1, 1)
  %p Never called on
- else
  %p #{time_ago_in_words(student.called_on)} ago

app/views/students/index.html.haml
= button_to "Pick Student", call_on_students_path, class: "button", method: "put"

%h1 Students:
- if @students == nil
  %p There are no students in your list
- else
  %ul#students= render @students

=simple_form_for @student, url: students_path do |f|
  =f.input :name
  =f.submit "Add Student", class: "button"